apiVersion: v2
name: testkube-runner
description: A Helm chart for the Testkube's Runner Agent
type: application
version: 2.4.3
appVersion: 2.3.0
dependencies:
- name: global
  version: 0.x.x-x
  repository: "file://../global"
