apiVersion: v2
name: testkube-runner
description: A Helm chart for the Testkube's Runner Agent
type: application
version: 2.6.2
appVersion: 2.6.2
dependencies:
- name: global
  version: 0.x.x-x
  repository: "file://../global"
