apiVersion: v2
name: testkube-api
description: A Helm chart for Testkube api
type: application
version: 2.7.0-rc.0
appVersion: 2.7.0-rc.0
dependencies:
  - name: global
    version: 0.1.3
    repository: "file://../global"
