apiVersion: v2
name: testkube-api
description: A Helm chart for Testkube api
type: application
version: 2.5.5
appVersion: 2.5.5
dependencies:
  - name: global
    version: 0.1.3
    repository: "file://../global"
