apiVersion: v2
name: testkube-api
description: A Helm chart for Testkube api
type: application
version: 2.4.4
appVersion: 2.4.4
dependencies:
  - name: global
    version: 0.1.3
    repository: "file://../global"
