apiVersion: v2
name: testkube
description: Testkube is an open-source platform that simplifies the deployment and management of automated testing infrastructure.
type: application
version: 2.6.1
appVersion: 2.6.1
dependencies:
  - name: testkube-operator
    version: 2.x.x-x
    repository: "file://../testkube-operator"
  - name: mongodb
    condition: mongodb.enabled
    version: 8.2.3-1
    repository: oci://us-east1-docker.pkg.dev/testkube-cloud-372110/testkube
  - name: postgresql
    condition: postgresql.enabled
    version: 0.1.0
    repository: oci://us-east1-docker.pkg.dev/testkube-cloud-372110/testkube
  - name: nats
    condition: testkube-api.nats.enabled
    version: 1.2.6-4
    repository: "file://./charts/nats"
  - name: testkube-api
    version: 2.x.x-x
    repository: "file://../testkube-api"
  - name: global
    version: 0.x.x-x
    repository: "file://../global"
