kind: TestWorkflowTemplate
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: distribute--evenly
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "19"
    helm.sh/hook-delete-policy: hook-failed,before-hook-creation
spec:
  config:
    name:
      description: optional group name for even distribution
      type: string
      default: ""
  pod:
    labels:
      distribute-evenly: "{{execution.id}}{{config.name}}"
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          distribute-evenly: "{{execution.id}}{{config.name}}"
