kind: TestWorkflowTemplate
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: official--gradle--beta
  labels:
    testkube.io/name: Gradle
    testkube.io/wizard: disabled
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "19"
    helm.sh/hook-delete-policy: hook-failed,before-hook-creation
    testkube.io/categories: Other
    testkube.io/description: Gradle
    testkube.io/icon: gradle
spec:
  config:
    version:
      description: Gradle version to use
      type: string
      default: 8.7.0-jdk21-alpine
    run:
      description: Run command
      type: string
      default: "gradle --no-daemon test"
  steps:
  - name: Run Gradle command
    run:
      image: {{`"gradle:{{ config.version }}"`}}
      shell: {{`"{{ config.run }}"`}}
