name: api-server-helm-releaser

on:
  push:
    tags: 
      # - "v[0-9]+.[0-9]+.[0-9]+"
      # - "v[0-9]+.[0-9]+.[0-9]+-*"
      - "vTesting[0-9]+.[0-9]+.[0-9]+"
      - "vTesting[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  releasing_helm_chart_api_server:
    runs-on: ubuntu-latest
    steps:
      - name: getting Tag name pushed.
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Editing helm-release repo with version based on a Tag pushed.
        run: |
          git clone https://kubeshop-bot:$GH_PUSH_TOKEN@github.com/kubeshop/helm-charts
          
          # Calling chart releaser script by passing needed folder name:
          # E.G. in order to relase api-server": ./chart_releaser.sh --helm-chart-folder api-server
          
          export GH_PUSH_TOKEN
          export RELEASE_VERSION

          cd helm-charts/scripts
          ./chart_releaser.sh --helm-chart-folder api-server

        env:
          GH_PUSH_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}