name: Deploy to GitHub Pages

concurrency:
  group: "mkdocs"
  cancel-in-progress: true

on:
  push:
    branches:
      - algolia-test
    # paths:
    #   - "docs/**"

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # - name: Install dependencies
      #   run: npm ci
      # - name: Build website
      #   run: npm run build

      # # Popular action to deploy to GitHub Pages:
      # # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     # Build output to publish to the `gh-pages` branch:
      #     publish_dir: ./docs/build
      #     # The following lines assign commit authorship to the official
      #     # GH-Actions bot for deploys to `gh-pages` branch:
      #     # https://github.com/actions/checkout/issues/13#issuecomment-724415212
      #     # The GH actions bot is used by default if you didn't specify the two fields.
      #     # You can swap them out with your own user credentials.
      #     user_name: github-actions[bot]
      #     user_email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: Algolia crawler creation and crawl
        # if: github.ref == 'refs/heads/main'
        uses: algolia/algoliasearch-crawler-github-actions@v1.0.10
        id: algolia_crawler
        with:
          crawler-user-id: ${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: "https://docs.testkube.io"
